version: "3"

services:
  mysql:
    image: mysql
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=foobar
      - MYSQL_DATABASE=db
    ports:
      - '3306:3306'